# ===========================================================================
#  setup_qemu_wsl.ps1
#  macOS VM via QEMU บน WSL2 (Windows)
#
#  ทางเลือกฟรี — ไม่ต้องซื้อ VMware
#  ใช้ QEMU + OpenCore bootloader รัน macOS Sonoma
#
#  Requirements:
#    - Windows 10 22H2+ หรือ Windows 11
#    - WSL2 enabled (wsl --install)
#    - KVM support (Intel VT-x / AMD-V) — ต้องเปิดใน BIOS
#    - ไฟล์ macOS installer (.dmg/.iso) + OpenCore EFI
#
#  จะสร้าง: helper scripts ใน WSL2 Ubuntu สำหรับ boot VM
#  จากนั้นใช้ SSH หรือ VNC เข้าไป build kext
# ===========================================================================

param(
    [string]$VmDir         = "$env:USERPROFILE\Documents\Virtual Machines\macOS-QEMU",
    [int]    $RamMB        = 8192,
    [int]    $Vcpus        = 4
)

Write-Host "=== MyIntelGPU — macOS VM via QEMU on WSL2 ===" -ForegroundColor Cyan

# ─────────────────────────────────────────────────────────────
# Step 1: Check WSL2
# ─────────────────────────────────────────────────────────────
Write-Host "`n[1/5] Checking WSL2..." -ForegroundColor Yellow

$wsl = wsl --status 2>&1 | Select-String "WSL 2"
if (-not $wsl) {
    Write-Host "WSL2 not detected. Installing..." -ForegroundColor Red
    Write-Host "Run in PowerShell (Admin) แล้วกลับมาใหม่:" -ForegroundColor Yellow
    Write-Host "  wsl --install"
    Write-Host "  wsl --set-default-version 2"
    exit 1
}
Write-Host "  WSL2 OK" -ForegroundColor Green

# ─────────────────────────────────────────────────────────────
# Step 2: Install QEMU + dependencies inside WSL
# ─────────────────────────────────────────────────────────────
Write-Host "`n[2/5] Installing QEMU + dependencies inside WSL..." -ForegroundColor Yellow

wsl -d Ubuntu -e bash -c @'
    sudo apt-get update -qq
    sudo apt-get install -y -qq \
        qemu-system-x86-64 \
        qemu-utils \
        python3 \
        python3-pip \
        wget \
        cpio \
        dmg2img \
        libguestfs-tools \
        sshpass \
        virt-manager \
        ovmf \
        mtools \
        dosfstools \
        build-essential \
        git \
        --no-install-recommends
    echo "QEMU version: $(qemu-system-x86_64 --version | head -1)"
'@

Write-Host "  QEMU installed" -ForegroundColor Green

# ─────────────────────────────────────────────────────────────
# Step 3: Create VM directory + download OpenCore
# ─────────────────────────────────────────────────────────────
Write-Host "`n[3/5] Creating VM directory + downloading OpenCore..." -ForegroundColor Yellow

New-Item -ItemType Directory -Path "$VmDir\firmware" -Force | Out-Null
New-Item -ItemType Directory -Path "$VmDir\shared" -Force | Out-Null

# Copy MyIntelGPU project into shared folder
Copy-Item -Recurse -Path ".\*" -Destination "$VmDir\shared\" -Force

# Download OpenCore (latest release) via WSL
wsl -d Ubuntu -e bash -c @"
    cd $(wslpath -a '$VmDir')
    mkdir -p firmware

    # Download OpenCore
    OC_URL=\$(curl -s https://api.github.com/repos/acidanthera/OpenCorePkg/releases/latest \
        | grep "browser_download_url.*RELEASE.zip" | cut -d'"' -f4)

    if [ -z "\$OC_URL" ]; then
        echo "Falling back to known OpenCore 1.0.0"
        OC_URL="https://github.com/acidanthera/OpenCorePkg/releases/download/1.0.0/OpenCore-1.0.0-RELEASE.zip"
    fi

    wget -q "\$OC_URL" -O /tmp/opencore.zip
    unzip -q -o /tmp/opencore.zip -d firmware/
    echo "OpenCore: \$(ls firmware/X64/EFI/OC/ -1 | head -5)"
"@

# Create OVMF firmware symlink
wsl -d Ubuntu -e bash -c @"
    ln -sf /usr/share/OVMF/OVMF_CODE.fd $(wslpath -a '$VmDir')/firmware/OVMF_CODE.fd
    ln -sf /usr/share/OVMF/OVMF_VARS.fd $(wslpath -a '$VmDir')/firmware/OVMF_VARS.fd
"@

# ─────────────────────────────────────────────────────────────
# Step 4: Create QEMU launch script (inside WSL)
# ─────────────────────────────────────────────────────────────
Write-Host "`n[4/5] Creating launch script..." -ForegroundColor Yellow

$qemuScript = @"
#!/bin/bash
# macOS VM — QEMU + OpenCore
# Auto-generated by setup_qemu_wsl.ps1
# Usage: ./macos-vm.sh [boot|install]

VM_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
RAM_MB="$RamMB"
VCPUS="$Vcpus"
CPU_CORE="\$VCPUS"
HDD="\$VM_DIR/macos.qcow2"
OVMF_CODE="\$VM_DIR/firmware/OVMF_CODE.fd"
OVMF_VARS="\$VM_DIR/firmware/OVMF_VARS.fd"
OC_EFI="\$VM_DIR/firmware/X64/EFI"
SHARED="\$VM_DIR/shared"
MACOS_ISO="\$1"           # ใส่ path ISO เป็น argument ถ้า install

# ─── CPU features (ต้องตรงกับ Intel Gen ที่เราจะ Fake) ───
# เลียนแบบ Coffee Lake (Gen9) i7-8700K
CPU_FEATURES="host,-invtsc,-ibpb,-stibp,-flushbyasid,-xsaves,-mpx,-pdpe1gb,-rdseed,-sgx,+ssse3,+sse4.2,+avx,+avx2,+aes,+pclmulqdq,+fsgsbase,+bmi1,+bmi2,+fma,+movbe,+popcnt"

# ─── Create HDD image ถ้ายังไม่มี ───
if [ ! -f "\$HDD" ]; then
    echo "Creating HDD image..."
    qemu-img create -f qcow2 "\$HDD" 80G
fi

# ─── QEMU Args ───
ARGS=(
    # Machine
    -machine q35,accel=kvm:tcg
    -global ICH9-LPC.disable_s3=1
    -global ICH9-LPC.disable_s4=1
    -smbios type=2,manufacturer="Apple Inc.",product="iMac19,1",version="1.0"
    -smbios type=0,vendor="Apple Inc.",version="1.0",date="11/20/2020",release=1
    -smbios type=1,manufacturer="Apple Inc.",product="iMac19,1",version="1.0",serial="C02XK0A8JG5H",uuid="6E6F7567-6874-2D48-6163-6B696E746F"
    -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"

    # CPU
    -cpu "\$CPU_FEATURES"
    -smp "cores=\$CPU_CORE,threads=1,sockets=1"

    # Memory
    -m "\$RAM_M"

    # OVMF (UEFI)
    -drive if=pflash,format=raw,readonly=on,file="\$OVMF_CODE"
    -drive if=pflash,format=raw,file="\$OVMF_VARS"

    # OpenCore Bootloader
    -drive id=OpenCore,if=virtio,format=raw,snapshot=on,file="\$OC_EFI"

    # macOS Disk
    -drive id=HDD,if=none,file="\$HDD",format=qcow2
    -device virtio-blk-pci,drive=HDD,bootindex=1

    # macOS Installer (ISO) — ถ้า specify
    $(if [ -n "\$MACOS_ISO" ] && [ -f "\$MACOS_ISO" ]; then
        echo '-drive id=installer,if=none,file="\$MACOS_ISO",format=raw'
        echo '-device ide-cd,drive=installer,bootindex=2'
    fi)

    # Shared folder (9p/virtio)
    -fsdev local,id=myintelgpu,path="\$SHARED",security_model=passthrough,readonly=off
    -device virtio-9p-pci,fsdev=myintelgpu,mount_tag=MyIntelGPU

    # Graphics (VNC remote desktop — ไม่ต้องมี physical display)
    -vga virtio
    -display none
    -vnc :0,password=on

    # Network
    -netdev user,id=net0,hostfwd=tcp::10022-:22,hostfwd=tcp::15900-:5900
    -device virtio-net-pci,netdev=net0

    # USB + Input
    -device piix3-usb-uhci
    -device usb-kbd
    -device usb-mouse

    # Serial console (for kernel debug log)
    -serial mon:stdio

    # Misc
    -device virtio-rng-pci
    -audiodev none,id=none
    -rtc base=localtime
    -boot menu=on
)

# ─── Launch ───
echo "=========================================="
echo " macOS VM Launcher"
echo "=========================================="
echo " VNC : localhost:5900  (password: macos)"
echo " SSH : ssh user@localhost -p 10022"
echo "=========================================="
echo " Inside VM, mount shared folder:"
echo "   sudo mount -t 9p -o trans=virtio MyIntelGPU /mnt/"
echo "   cd /mnt && make"
echo "=========================================="

qemu-system-x86_64 "\${ARGS[@]}" &
QEMU_PID=\$!

# Set VNC password
sleep 2
echo "set_password vnc macos" | socat - UNIX-CONNECT:/tmp/qemu-vnc-\$QEMU_PID 2>/dev/null || \
    qemu-system-x86_64 "\${ARGS[@]}" -qmp tcp:localhost:14445,server,nowait

wait \$QEMU_PID
"@

$qemuScriptPath = "$VmDir\macos-vm.sh"
$qemuScript | Set-Content -Path $qemuScriptPath -Encoding ASCII

# ─────────────────────────────────────────────────────────────
# Step 5: Create Connect script (Windows-side shortcut)
# ─────────────────────────────────────────────────────────────
Write-Host "`n[5/5] Creating Windows helper scripts..." -ForegroundColor Yellow

# Connect via VNC Viewer
@"
@echo off
REM เปิด VNC viewer เชื่อมต่อ macOS VM
start vncviewer.exe localhost:15900
"@ | Set-Content -Path "$VmDir\connect_vnc.bat" -Encoding ASCII

# Copy project files to shared folder
Write-Host "  Copying MyIntelGPU source to shared folder..."
if (Test-Path ".\MyIntelGPU.hpp") {
    Copy-Item -Path ".\MyIntelGPU.hpp" -Destination "$VmDir\shared\" -Force
    Copy-Item -Path ".\MyIntelGPU.cpp" -Destination "$VmDir\shared\" -Force
    Copy-Item -Path ".\Info.plist" -Destination "$VmDir\shared\" -Force
    Copy-Item -Path ".\Makefile" -Destination "$VmDir\shared\" -Force
}

# ─────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "✅ QEMU setup complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "VM Dir : $VmDir"
Write-Host ""
Write-Host "To boot VM (install macOS ครั้งแรก):"
Write-Host "  wsl -d Ubuntu -e bash"
Write-Host "  cd `$(wslpath -a '$VmDir')"
Write-Host "  ./macos-vm.sh /path/to/macOS.iso"
Write-Host ""
Write-Host "To boot VM (ครั้งต่อมา / ไม่ต้อง install):"
Write-Host "  ./macos-vm.sh"
Write-Host ""
Write-Host "Connect:"
Write-Host "  VNC : $VmDir\connect_vnc.bat    (password: macos)"
Write-Host "  SSH : ssh user@localhost -p 10022"
Write-Host ""
Write-Host "Build kext inside VM:"
Write-Host "  sudo mount -t 9p -o trans=virtio MyIntelGPU /mnt/"
Write-Host "  cd /mnt && make"
Write-Host "  sudo kextutil MyIntelGPU.kext"
Write-Host ""
Write-Host "╔══════════════════════════════════════════════╗"
Write-Host "║  ปัญหา macOS ISO:                            ║"
Write-Host "║  ต้องหา macOS installer เอง                  ║"
Write-Host "║  (Apple ไม่ให้ download ฟรีบน non-Apple HW)   ║"
Write-Host "║                                              ║"
Write-Host "║  GitHub Actions = ไม่ต้องหา VM เลย           ║"
Write-Host "║  push code → build บน macos-14 runner ฟรี!  ║"
Write-Host "╚══════════════════════════════════════════════╝"
Write-Host "========================================" -ForegroundColor Cyan
